[package]
name = "maze_generation"
version = "0.1.0"
authors = ["Jack92829 <jack92829@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
